title: EDA²"习芯堂"第三期多元化全流程EDA软件培训 2025
page-top-title: EDA²"习芯堂"第三期多元化全流程EDA软件培训 2025
top-section-bg-text: EDA²"习芯堂"第三期多元化全流程EDA软件培训
home-subtitle: EDA²"习芯堂"第三期多元化全流程EDA软件培训&ensp;|&ensp;EDA² "Xixin Academy" 3rd Session Multi-Platform Full-Process EDA Software Training
copyright-text: '&copy; Fudan University National Key Laboratory of Integrated Chips and Systems 2025. All Rights Reserved.'
github-link: https://github.com/Young-Teams/Young-Teams.github.io
license-link: https://github.com/Young-Teams/Young-Teams.github.io/blob/main/LICENSE
